### ISSUE TITLE
typo: read writes -> read-only right

### ISSUE THREAD

**Issue by jonassmedegaard** [ontola/atomic-data-docs#70]
Web page https://docs.atomicdata.dev/invitations.html contains this:
> provides read writes by default

"writes" *sounds* the same as "rights" but very different meaning :-)

Also, I suggest clarifying further by dscribing as "read-only right" to emphasize reducing to that one single right.

**Comment by joepio** [comment]
Thanks for pointing out the typo!

Regarding your second point, about using `read-only right`: I think it might be harmful to rename this property, as `read-only` can always be combined with `write`. And when you have both, the `read-only` no longer makes sense, I think - or they should be mutually exclusive.

**Comment by jonassmedegaard** [comment]
fair enough :-)
