### ISSUE TITLE
typo in docs about JSON-LD: an -> can

### ISSUE THREAD

**Issue by jonassmedegaard** [ontola/atomic-data-docs#90]
The web page https://docs.atomicdata.dev/core/json-ad.html contains this:
> Although you an use various serialization formats for Atomic Data,

Please replace "an" with "can" :-)

**Comment by jonassmedegaard** [comment]
...and further down in same paragraph:
> It is designed to feel familiar to developers an to be easy

Please here replace "an" with "and"

**Comment by joepio** [comment]
Thanks, fixed!
