### ISSUE TITLE
How to prevent dependency on Ontology hosters

### ISSUE THREAD

**Issue by hoijui** [ontola/atomic-data-docs#99]
In AD, ontologies (their resources) have to be reachable under their URL. What to do, if some hoster of an important ontology goes offline, or is very slow, or changes the ontology without changing the version.
If I were some company dealing with lots of data, I would not want my whole database to be dependent on the stability of a variety of other organizations, of which.. most likely, I do not know, how reliant they are. I would have to mirror all these ontologies onto my own servers, and use DNS trickery, though that would also only work within my network. in the end, I would probably end up copying all foreign ontologies into my own namespace/under my domain, and if everyone does that, it would effectively make AD non-linked data.

I vaguely remember you talking about IPFS ... is it a possible solution for this issue?

... is this an issue at all?

**Comment by jonassmedegaard** [comment]
IPFS only shifts to relying on a different foundation that then still needs to be reliable.

What I mean is, believers of IPFS would argue that it is failsafe, but so would each domain owner.

I think there is fundamentally no answer to the question of "How to prevent dependency..." but what can be reasonably answered instead is "How to mitigate dependency..." where the answer is to make backups - i.e. reliably mirroring content, with tracking of when in time that backup was valid, and for how long (according to metadata in the HTTP transactions) it was claimed to sustain valid.

**Comment by jonassmedegaard** [comment]
Concrete user experience might be, that an Atomic Server can optionally maintain a cache of external data referenced by local data (purging it when no longer referenced).
Depending on user interfaces used, Atomic Server might notify the user a) when references to external data is noticed that the user might want to enable caching of, and b) when diskspace runs low so the user might want to purge cached data.
User might then request filling cache once, or to "keep it hot" - i.e. update routinely.
User might specify some constraints - e.g. a limit on how frequent to update (to account for crazy low expiry times), or skip updating when on battery or using expensive network interfaces (e.g. for Atomic Server running on a laptop).

**Comment by joepio** [comment]
(on my phone, short reply) 

- **Cache dependencies**: Atomic Server stores a copy of every class and property that it uses. The /path endpoint then allows clients to fetch these from servers that have cached it. 
- **central backup server**: I think it might be a good idea to have an ontologies.atomicdata.dev that serves to back stuff up

**Comment by hoijui** [comment]
wow. cool guys! :-)
I am fully satisfied... more then!

**Comment by hoijui** [comment]
Do you have a FAQ for things like this already, or do you prefer to use issues only, for documenting things like this?

**Comment by joepio** [comment]
> Do you have a FAQ for things like this already, or do you prefer to use issues only, for documenting things like this? I saw there is https://www.atomicdata.com/faq/ ... would it fit there?

That's not my website, although we do share a name though! But I think I could put it in the [schema FAQ](https://docs.atomicdata.dev/schema/faq.html).

**Comment by hoijui** [comment]
ups! :D
c&p error.. yep that is what I wanted to copy.

**Comment by joepio** [comment]
I've added the text to the FAQ, closing this for now! Feel free to comment if there's a new insight of course :)
